FROM python:3.12-slim


RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    wget \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .
# The model will download automatically on first run via your lifespan code

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
