FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Run migrations and start the server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8010"]
