FROM python:3.12-slim

# Step 1: System Updates (The OpenCV/MediaPipe prerequisites)
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    wget \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Step 2: API Installation (The heavy Python libraries)
# Note: We use requirements_ai.txt to keep it separate
COPY requirements_ai.txt .
RUN pip install --no-cache-dir --default-timeout=1000 -r requirements_ai.txt

COPY main.py .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8008"]
